from enum import StrEnum

class PickFailureCode(StrEnum):
    NONE = 'NONE'
    CANCELED = 'CANCELED'

    NO_CANDIDATE = 'NO_CANDIDATE'
    WIDTH_INVALID = 'WIDTH_INVALID'
    IK_FAIL = 'IK_FAIL'
    PATH_COLLISION = 'PATH_COLLISION'
    CONTROLLER_REJECTED = 'CONTROLLER_REJECTED'
    GRASP_DROP = 'GRASP_DROP'